### PR TITLE
Dashboard

### PR DESCRIPTION
**Pull request by NWalker4483**
Add with some pretty graphs and stats

### CODE REVIEW

**Review by danfunk — CHANGES_REQUESTED** [review]
Sweet heavenly goodness Nile.  You can't go dumping a whole nother library into our github repository.  We'll have to look at another way to handle our javascript dependencies so they don't clutter up the repository and we can manage upgrades over time (if needed).    I did some digging, and I think the best method would be to add flask-bower and use that to add in dependencies, add something to readme on how to install javacsript dependencies, and then remove all of these files from the pull request.

**Review by danfunk — COMMENTED** [review]
When adding in python dependencies, do so with "pipenv install xxxx" - then it ends up in the pipfile, which keeps all of our development environments in synch, and allows us to properly build the docker container for deployment.

**Comment by NWalker4483** [comment]
😅 Didn't think about that. I'm cleaning out the leftovers now

**Comment by danfunk** [comment]
Another thought when demoing today - please be sure to remove any and all links or navigation items that aren't in use.  So all the nav items to the left, and there seems to be an attribution at the bottom of the page to someone else.  I don't mind saying we reused someone elses designs, but this seems to the credit of all of our efforts to someone else.

**Comment by NWalker4483** [comment]
Noted I've removed any unused links and code but I'm in the car atm so will
push once we've stopped by wifi.

**Comment by NWalker4483** [comment]
For reference I worked off of a quick start project from
https://www.creative-tim.com/product/argon-design-system

**Comment by NWalker4483** [comment]
Is that going to be an issue?

**Comment by danfunk** [comment]
No, that's not an issue at all,  it was a good idea, and it let us clean up the ui substantially, and get a more professional look and feel.  You did the right thing Nile.  Overall there is a lot that is good here.  Just my job at the moment to be critical.  Overall very pleased with your efforts, as evidenced by my showing your work to what might well be our most valuable client.

**Pull request merged**
